--TESTING CODE
--VIDEO LENGTH: LESS THAN 15 MINUTES, MORE THAN 45 MINUTES
SELECT VIDEO_NAME, TRUNC(LENGTH/60,0) || ':'|| MOD(LENGTH, 60) AS LENGTH FROM VIDEO WHERE LENGTH < (15*60);
SELECT VIDEO_NAME, TRUNC(LENGTH/60,0) || ':'|| MOD(LENGTH, 60) AS LENGTH FROM VIDEO WHERE LENGTH > (45*60);

--USER AND THERE VIDEO with screening status
SELECT USER_NAME AS Contributor, VIDEO_NAME, CATEGORY, TRUNC(LENGTH/60,0) || ':'|| MOD(LENGTH, 60) AS LENGTH, SCREENING 
FROM "USER" NATURAL JOIN VIDEO ORDER BY USER_NAME;

--CHANNEL, CHANNEL OWNER AND ITS VIDEOS
SELECT C.CHANNEL_NAME AS CHANNEL, U.USER_NAME AS OWNER, V.VIDEO_NAME AS VIDEOS, TRUNC(V.LENGTH/60,0) || ':'|| MOD(V.LENGTH, 60) AS LENGTH 
FROM CHANNEL C, "USER" U, VIDEO V
WHERE C.CHANNEL_ID = U.CHANNEL_ID
AND C.CHANNEL_ID = V.CHANNEL_ID;

--PLAYLIST AND ITS ITEMS
SELECT P.PLAYLIST_NAME, V.VIDEO_NAME, TRUNC(V.LENGTH/60,0) || ':'|| MOD(V.LENGTH, 60) AS LENGTH 
FROM VIDEO V, PLAYLIST P NATURAL JOIN PLAYLISTITEM I
WHERE I.VIDEO_ID = V.VIDEO_ID;

--CHATROOM AND ITS MEMBERS
SELECT CHATROOM_NAME, USER_NAME FROM CHATROOM NATURAL JOIN CHATROOM_MEMBER NATURAL JOIN "USER";

--SUBCRIPTION
--CHANNEL
SELECT C.CHANNEL_NAME AS CHANNEL, U.USER_NAME AS FOLLOWER 
FROM SUBSCRIPTION S, CHANNEL C, "USER" U
WHERE S.FOLLOWED_ID = C.CHANNEL_ID
AND S.USER_ID = U.USER_ID;
--USER
SELECT U.USER_NAME AS "USER", F.USER_NAME AS FOLLOWER
FROM SUBSCRIPTION S, "USER" F, "USER" U
WHERE S.FOLLOWED_ID = U.USER_ID
AND S.USER_ID = F.USER_ID;

SELECT U.USER_NAME FROM CHATROOM C JOIN CHATROOM_MEMBER USING (CHATROOM_ID)
JOIN "USER" U USING (USER_ID)
JOIN CHANNEL C USING (CHANNEL_ID)
JOIN VIDEO V USING (CHANNEL_ID)
JOIN PLAYLISTITEM USING (VIDEO_ID)
JOIN PLAYLIST USING (PLAYLIST_ID);