--1. USER TABLE
create table "USER"
(USER_ID varchar2(7), 
USER_NAME varchar2(20) not null, 
LICENSE varchar2(15) default 'PERSONAL',
Channel_ID varchar2(7), 
email varchar2(50) not null,
constraint USER_ID_PK primary key (USER_ID),
constraint LICENSE_CHK check(LICENSE in('PERSONAL','BUSINESS'))enable,
constraint email_UK unique(email));
SELECT * FROM "USER";


--2. VIDEO TABLE
CREATE TABLE VIDEO
(VIDEO_ID VARCHAR2(7),
  CONSTRAINT VIDEO_ID_PK PRIMARY KEY (VIDEO_ID),
VIDEO_NAME VARCHAR2(20) NOT NULL,
USER_ID VARCHAR2(7), --FK
CHANNEL_ID VARCHAR2(7), --FK
CATEGORY VARCHAR2(15), --CK
  CONSTRAINT VIDEO_CATEGORY_CK CHECK 
    (CATEGORY IN ('MUSIC', 'SPORTS', 'GAMING', 'FILMS', 'TV SHOWS', 'NEWS')),
LENGTH NUMBER(6) NOT NULL, --HOW MANY SECONDS THIS VIDEO HAS
SCREENING VARCHAR2(1) DEFAULT 'N',
  CONSTRAINT VIDEO_SCREENING_CK CHECK (SCREENING IN ('Y', 'N')));
SELECT * FROM VIDEO;

--3. CHANNEL
CREATE TABLE CHANNEL
(CHANNEL_ID VARCHAR2(7),
CHANNEL_NAME VARCHAR2(20) NOT NULL,
CATEGORY VARCHAR2(15),
  CONSTRAINT CHANNEL_CATEGORY_CK CHECK 
    (CATEGORY IN ('MUSIC', 'SPORTS', 'GAMING', 'FILMS', 'TV SHOWS', 'NEWS')),
DESCRIPTION VARCHAR2(140),
CONSTRAINT CHANNEL_ID_PK PRIMARY KEY(CHANNEL_ID));
SELECT * FROM CHANNEL;

--4. PLAYLIST
CREATE TABLE PLAYLIST
(PLAYLIST_ID VARCHAR2(7),
PLAYLIST_NAME VARCHAR(20) NOT NULL,
CATEGORY VARCHAR2(15),
  CONSTRAINT PLAYLIST_CATEGORY_CK CHECK 
    (CATEGORY IN ('MUSIC', 'SPORTS', 'GAMING', 'FILMS', 'TV SHOWS', 'NEWS')),
CONSTRAINT PLAYLIST_ID_PK PRIMARY KEY (PLAYLIST_ID));
SELECT * FROM PLAYLIST;

--5. PL ITEM
CREATE TABLE PLAYLISTITEM
(PLAYLIST_ID VARCHAR2(7),
VIDEO_ID VARCHAR2(7),
CONSTRAINT PLAYLISTITEM_ID_PK PRIMARY KEY (PLAYLIST_ID,VIDEO_ID));
SELECT * FROM PLAYLISTITEM;

--6.SUBSCRIPTION
CREATE TABLE SUBSCRIPTION
(USER_ID VARCHAR2(7),
FOLLOWED_ID VARCHAR2(7),
CONSTRAINT SUBSCRIPTION_ID_PK PRIMARY KEY (USER_ID,FOLLOWED_ID));
SELECT * FROM SUBSCRIPTION;

--7. CHATROOM
CREATE TABLE CHATROOM
(CHATROOM_ID VARCHAR2(7),
  CONSTRAINT CHATR_ID PRIMARY KEY (CHATROOM_ID),
CHATROOM_NAME VARCHAR2(20) NOT NULL,
CATEGORY VARCHAR2(15),
  CONSTRAINT CHATR_CATEGORY_CK CHECK
    (CATEGORY IN ('MUSIC', 'SPORTS', 'GAMING', 'FILMS', 'TV SHOWS', 'NEWS')));
SELECT * FROM CHATROOM;

--8.CR MEMBER 
CREATE TABLE CHATROOM_MEMBER
(CHATROOM_ID VARCHAR2(7),
USER_ID VARCHAR2(7),
  CONSTRAINT CHATMBR_ID_PK PRIMARY KEY (CHATROOM_ID, USER_ID));
  SELECT * FROM CHATROOM_MEMBER;


--FOREIGN KEY
--USER
ALTER TABLE "USER" ADD CONSTRAINT USER_CHANNELID_FK FOREIGN KEY (Channel_ID) REFERENCES CHANNEL (CHANNEL_ID);
--VIDEO
ALTER TABLE VIDEO ADD CONSTRAINT VIDEO_USERID_FK FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);
ALTER TABLE VIDEO ADD CONSTRAINT VIDEO_CHANNELID_FK FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL (CHANNEL_ID);
--PLAYLIST ITEM
ALTER TABLE PLAYLISTITEM ADD CONSTRAINT PLITEM_PLAYLISTID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST (PLAYLIST_ID);
ALTER TABLE PLAYLISTITEM ADD CONSTRAINT PLITEM_VIDEOID_FK FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO (VIDEO_ID);
--SUBSCRIPTION
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT SUBSCRIP_USERID_FK FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT SUBSCRIP_FOLLOWED_USER_FK FOREIGN KEY (FOLLOWED_ID) REFERENCES "USER" (USER_ID);
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT SUBSCRIP_FOLLOWED_CHANNEL_FK FOREIGN KEY (FOLLOWED_ID) REFERENCES CHANNEL (CHANNEL_ID);
--CHATROOM MENBER LIST
ALTER TABLE CHATROOM_MEMBER ADD CONSTRAINT CHATMBR_CHATRID_FK FOREIGN KEY (CHATROOM_ID) REFERENCES CHATROOM (CHATROOM_ID);
ALTER TABLE CHATROOM_MEMBER ADD CONSTRAINT CHATMBR_USERID_FK FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID);